"""empty message

Revision ID: 10695a873791
Revises: 
Create Date: 2018-08-16 09:47:57.325754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10695a873791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=32), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.Column('time_modify', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
